### ISSUE TITLE
pactVerify Gradle task not working on Gradle 7.1

### ISSUE THREAD

**Issue by georgeharley** [pact-foundation/pact-jvm#1429]
This looks like it might be related to #1374 

Using a Gradle wrapper at 7.1 and version 4.1.26 of the "au.com.dius.pact" Gradle plugin, the `pactVerify` task fails. 

```bash
$ ./gradlew clean build pactVerify

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.4)

2021-09-06 14:40:55.421  INFO 19673 --- [           main] c.d.p.c.p.p.PactProviderApplication      : Starting PactProviderApplication using Java 11.0.7 on ...

. . .

> Task :startBootApp

. . .

2021-09-06 14:40:56.477  INFO 19673 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2021-09-06 14:40:56.491  INFO 19673 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-09-06 14:40:56.492  INFO 19673 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.52]
2021-09-06 14:40:56.554  INFO 19673 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-09-06 14:40:56.555  INFO 19673 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1067 ms
2021-09-06 14:40:57.016  INFO 19673 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2021-09-06 14:40:57.063  INFO 19673 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2021-09-06 14:40:57.075  INFO 19673 --- [           main] c.d.p.c.p.p.PactProviderApplication      : Started PactProviderApplication in 2.129 seconds (JVM running for 2.662)

> Task :pactVerify_pactProvider FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':pactVerify_pactProvider' (type 'PactVerificationTask').
  - In plugin 'au.com.dius.pact' type 'au.com.dius.pact.provider.gradle.PactVerificationTask' property 'providerToVerify' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.1/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - In plugin 'au.com.dius.pact' type 'au.com.dius.pact.provider.gradle.PactVerificationTask' property 'verifier' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.1/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 7s
7 actionable tasks: 7 executed
```

When the Gradle wrapper was switched to version 6.8 (with no other changes made) the `pactVerify` worked fine again.

**Comment by uglyog** [comment]
To use Gradle 7+, use version 4.2.10

**Comment by georgeharley** [comment]
Thanks @uglyog, I must have missed that in the docs. Switching to 4.2.x did indeed allow using a Gradle 7.1 wrapper but there was a bit of a glitch in the plan that I'm a little confused over. My simple consumer project borrows heavily from the test code examples provided in the doc for Pact JVM JUnit 5 support and uses the `org.apache.http.client.fluent.Request` class as shown in the section on [injecting the mock server into tests](https://github.com/pact-foundation/pact-jvm/tree/master/consumer/junit5#injecting-the-mock-server-into-the-test). 

```java
    @Test
    @PactTestFor(pactMethod = "getPerson")
    void getPersonFromProvider(MockServer mockServer) throws IOException {
        HttpResponse httpResponse = Request.Get(mockServer.getUrl() + "/person").execute().returnResponse();
        assertThat(httpResponse.getStatusLine().getStatusCode(), is(equalTo(200)));
 
        . . .

    }
```

When using Pact JVM 4.1.26 and Gradle 6.8 the above test code works great. Switching to Pact JVM 4.2.11 and Gradle 7.1 causes a compile error in the test code as shown below because the `org.apache.http.client.fluent.Request` can no longer be found.

```bash
$ ./gradlew clean build --refresh-dependencies

> Task :compileTestJava
/Users/gharle1/code/workspace/pact/pact-broker-demo/pact-consumer/src/test/java/com/discover/pact/consumer/controller/ConsumerControllerPactTest.java:14: error: package org.apache.http.client.fluent does not exist
import org.apache.http.client.fluent.Request;
                                    ^
warning: unknown enum constant AnnotationTarget.CLASS
  reason: class file for kotlin.annotation.AnnotationTarget not found
warning: unknown enum constant AnnotationTarget.FUNCTION
warning: unknown enum constant AnnotationRetention.RUNTIME
  reason: class file for kotlin.annotation.AnnotationRetention not found
warning: unknown enum constant AnnotationRetention.RUNTIME
warning: unknown enum constant AnnotationTarget.FUNCTION
warning: unknown enum constant AnnotationTarget.PROPERTY_GETTER
warning: unknown enum constant AnnotationTarget.PROPERTY_SETTER
/Users/gharle1/code/workspace/pact/pact-broker-demo/pact-consumer/src/test/java/com/discover/pact/consumer/controller/ConsumerControllerPactTest.java:48: error: cannot find symbol
        HttpResponse httpResponse = Request.Get(mockServer.getUrl() + "/person").execute().returnResponse();
                                    ^
  symbol:   variable Request
  location: class ConsumerControllerPactTest
2 errors
7 warnings

> Task :compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 27s
6 actionable tasks: 6 executed
```

The output of `./gradlew dependencies` for both scenarios (PactJVM 4.1.26/Gradle 6.8 and PactJVM4.2.11/Gradle 7.1) indicates that the **org.apache.httpcomponents:fluent-hc:4.5.13** dependency is getting pulled in yet this test compile error always occurs for the latter scenario. To workaround the problem I've had to add **org.apache.httpcomponents:fluent-hc:4.5.13** as an explicit dependency...

```groovy
dependencies {

        . . .

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'commons-io:commons-io:2.11.0'
	testImplementation 'au.com.dius.pact.consumer:junit5:4.2.11'
	testImplementation 'org.apache.httpcomponents:fluent-hc:4.5.13'
}
```

Is this a known issue with the Pact JVM 4.2.x release train?

**Comment by uglyog** [comment]
Pact-JVM doesn't actually use the fluent HTTP classes, and does not actually export that library. I think that it worked on 4.1.x/Gradle 6.8 is just a side effect of some of the tests using it and they were declared in the test class path. 

With Gradle 7 the dependencies are stricter, and 4.2.x has moved to use the implementation/api Gradle declarations so dependencies don't leak.

You should declare all the dependencies you use directly in your tests.

**Comment by georgeharley** [comment]
Thanks for the explanation @uglyog. Closing issue now.
